name: Update README Progress

on:
  push:
    branches:
      - main  # Ändere dies zu deinem Standardbranch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Skript ausführen, um den Fortschritt zu berechnen und README.md zu aktualisieren
      - name: Update README
        run: |
          python update_progress.py

      # Änderungen in das Repository pushen
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update progress in README" || echo "No changes to commit"
          git push || echo "No changes to push"
