name: Update README Progress

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Pillow

      - name: Generate Progress Image
        run: |
          python generate_progress_image.py
          git add progress.png
          git commit -m "Update progress image"
          git push
