name: Update README Progress

on:
  push:
    branches:
      - main  # Ändere dies zu deinem Standardbranch

permissions:
  contents: write  # Schreibberechtigungen für Repository-Inhalte

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Pillow

      - name: Generate Progress Image and Update README
        run: python update_progress.py  # Korrigierter Dateiname

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md progress.png  # Füge README.md hinzu
          git commit -m "Update progress image and README"
          git push
